import type { Comment, Dj, EngineGenre, LiveShow, Mix, Track } from "./types";
import { hashString } from "./utils";
import { WORLD_LIVE, WORLD_DJS, worldDj, worldLive } from "./feeds";

export const GENRES = [
  "UK Garage",
  "2-Step",
  "Drum & Bass",
  "Jungle",
  "Grime",
  "Techno",
  "House",
  "Bassline",
  "Breaks",
  "UK Funky",
  "Disco",
  "Electro",
  "Broken Beat",
  "Industrial",
] as const;

export const CITIES = [
  { slug: "london", name: "London" },
  { slug: "manchester", name: "Manchester" },
  { slug: "bristol", name: "Bristol" },
  { slug: "leeds", name: "Leeds" },
  { slug: "birmingham", name: "Birmingham" },
  { slug: "glasgow", name: "Glasgow" },
  { slug: "liverpool", name: "Liverpool" },
  { slug: "nottingham", name: "Nottingham" },
  { slug: "sheffield", name: "Sheffield" },
  { slug: "cardiff", name: "Cardiff" },
  { slug: "brighton", name: "Brighton" },
] as const;

const c = (
  id: string,
  user: string,
  text: string,
  t: number,
): Comment => ({ id, user, text, t });

const tr = (t: number, title: string): Track => ({ t, title });

export const DJS: Dj[] = [
  {
    id: "nia-vale",
    name: "Nia Vale",
    handle: "niavale",
    city: "London",
    citySlug: "london",
    photo: "/art/djs/nia-vale.jpg",
    show: "Peckham Steppers",
    genres: ["UK Garage", "2-Step"],
    followers: 18420,
    bio: "Peckham-born selector holding down 2-step in south London basements since 2019. If it still hits at 4am on the 36 bus, it goes in the bag.",
  },
  {
    id: "kieran-moss",
    name: "Kieran Moss",
    handle: "kieranmoss",
    city: "Manchester",
    citySlug: "manchester",
    photo: "/art/djs/kieran-moss.jpg",
    show: "Northern Frequencies",
    genres: ["Techno"],
    followers: 22110,
    bio: "Ancoats warehouse resident. Four-to-the-floor, no gimmicks, rooms that still smell of the mill. Peak-time sets built to last past sunrise.",
  },
  {
    id: "yasmin-reed",
    name: "Yasmin Reed",
    handle: "yasminreed",
    city: "Bristol",
    citySlug: "bristol",
    photo: "/art/djs/yasmin-reed.jpg",
    show: "Bristol Junglist",
    genres: ["Jungle", "Drum & Bass"],
    followers: 26780,
    bio: "Stokes Croft junglist. Amen science, reggae weight, and the Bristol roll that never left. Hosts a monthly at The Lanes.",
  },
  {
    id: "tobi-lane",
    name: "Tobi Lane",
    handle: "tobilane",
    city: "Leeds",
    citySlug: "leeds",
    photo: "/art/djs/tobi-lane.jpg",
    show: "Afters at 4",
    genres: ["Bassline", "UK Garage"],
    followers: 15340,
    bio: "Chapeltown bassline, UKG rewinds, and the kind of afters that start when other cities go home. Leeds does not clock off.",
  },
  {
    id: "asha-quinn",
    name: "Asha Quinn",
    handle: "ashaquinn",
    city: "Glasgow",
    citySlug: "glasgow",
    photo: "/art/djs/asha-quinn.jpg",
    show: "Low Room",
    genres: ["Broken Beat", "House"],
    followers: 9820,
    bio: "Finnieston keys and broken beat. Asha treats the booth like a piano stool — left hand on the filter, right hand on the night.",
  },
  {
    id: "jayce-hollow",
    name: "Jayce Hollow",
    handle: "jaycehollow",
    city: "Birmingham",
    citySlug: "birmingham",
    photo: "/art/djs/jayce-hollow.jpg",
    show: "Signal Hours",
    genres: ["Grime", "Bass"],
    followers: 31200,
    bio: "Digbeth pirate energy. Grime instrumentals, 140 weaponry, and the Midlands bassline the south still pretends it invented.",
  },
  {
    id: "maren-cole",
    name: "Maren Cole",
    handle: "marencole",
    city: "Liverpool",
    citySlug: "liverpool",
    photo: "/art/djs/maren-cole.jpg",
    show: "All Night Social",
    genres: ["Disco", "House"],
    followers: 12150,
    bio: "Baltic Triangle disco. Vinyl-only warm-ups that turn into nine-hour socials. The floor never asks what year it is.",
  },
  {
    id: "dex-palmer",
    name: "Dex Palmer",
    handle: "dexpalmer",
    city: "Nottingham",
    citySlug: "nottingham",
    photo: "/art/djs/dex-palmer.jpg",
    show: "Foundry Cuts",
    genres: ["Breaks"],
    followers: 7640,
    bio: "Sneinton breaks lifer. Nu-skool, electro, and the ugly swing that makes a Thursday feel illegal.",
  },
  {
    id: "saffron-ibe",
    name: "Saffron Ibe",
    handle: "saffronibe",
    city: "London",
    citySlug: "london",
    photo: "/art/djs/saffron-ibe.jpg",
    show: "East End Pressure",
    genres: ["UK Funky", "House"],
    followers: 19880,
    bio: "Hackney funky. Soca-tempo house, east London percussion, and the pressure that starts on the overground home.",
  },
  {
    id: "ellis-crowe",
    name: "Ellis Crowe",
    handle: "elliscrowe",
    city: "Sheffield",
    citySlug: "sheffield",
    photo: "/art/djs/ellis-crowe.jpg",
    show: "Blade",
    genres: ["Industrial", "Techno"],
    followers: 14300,
    bio: "Kelham Island industrial. Steel, steam, 136bpm. Ellis builds sets like a foundry shift — long, hot, no small talk.",
  },
  {
    id: "rio-bennett",
    name: "Rio Bennett",
    handle: "riobennett",
    city: "Cardiff",
    citySlug: "cardiff",
    photo: "/art/djs/rio-bennett.jpg",
    show: "Civic Bass",
    genres: ["Drum & Bass"],
    followers: 10940,
    bio: "Grangetown rollers. Liquid into tear-out without the identity crisis. Cardiff's civic centre after dark.",
  },
  {
    id: "lana-voss",
    name: "Lana Voss",
    handle: "lanavoss",
    city: "Brighton",
    citySlug: "brighton",
    photo: "/art/djs/lana-voss.jpg",
    show: "Seafront Closed",
    genres: ["Electro", "Breaks"],
    followers: 8720,
    bio: "Kemptown electro. Seafront afters when the clubs have packed down and the wind is doing percussion.",
  },
];

export const MIXES: Mix[] = [
  {
    id: "peckham-steppers-084",
    title: "Peckham Steppers 084",
    djId: "nia-vale",
    show: "Peckham Steppers",
    artwork: "/art/mixes/peckham-steppers.jpg",
    city: "London",
    citySlug: "london",
    genres: ["UK Garage", "2-Step"],
    engine: "ukg",
    bpm: 132,
    duration: 3724,
    plays: 48210,
    likes: 3210,
    uploadedAt: "2026-08-22T21:00:00Z",
    featured: true,
    seed: 84021,
    tags: ["2-step", "south london", "unreleased"],
    description:
      "Monthly 2-step from the Cellar booth. Skippy kicks, MJ Cole DNA, and three unreleased white labels that will not be on any playlist.",
    tracklist: [
      tr(0, "Nia Vale — Warmup Dub (unreleased)"),
      tr(214, "Wookie — Battle (Cellar re-edit)"),
      tr(512, "MJ Cole — Sincere (steppers cut)"),
      tr(804, "El-B — Buck & Bury"),
      tr(1102, "Nia Vale — Night Bus VIP"),
      tr(1488, "Zed Bias — Neighbourhood (refix)"),
      tr(1860, "Tuff Jam — Tune In (dub)"),
      tr(2288, "Nia Vale — Rinse Bag 3"),
      tr(2710, "Artful Dodger — Rewind (steppers)"),
      tr(3180, "Nia Vale — 36 Home"),
    ],
    comments: [
      c("n1", "southside.step", "that skip on the third tune is criminal", 540),
      c("n2", "bus_36", "heard this coming off the overground. had to find it", 0),
      c("n3", "kieran.m", "peckham doing it proper", 1880),
    ],
  },
  {
    id: "night-bus-home",
    title: "Night Bus Home",
    djId: "nia-vale",
    show: "Peckham Steppers",
    artwork: "/art/mixes/night-bus.jpg",
    city: "London",
    citySlug: "london",
    genres: ["UK Garage", "2-Step"],
    engine: "ukg",
    bpm: 130,
    duration: 5412,
    plays: 29104,
    likes: 2144,
    uploadedAt: "2026-07-11T23:40:00Z",
    seed: 36130,
    tags: ["afters", "2-step", "closedown"],
    description:
      "A closedown set for the last 36. Soft drums, sub that sits under conversation, nothing that needs a rewind at 4am.",
    tracklist: [
      tr(0, "Nia Vale — Lights Down"),
      tr(420, "Grant Nelson — Stepper's Dub"),
      tr(980, "Nia Vale — Quiet Bag"),
      tr(1540, "Sunship — Try Me Out (dub)"),
      tr(2210, "Nia Vale — Lower Marsh"),
      tr(2980, "Wookie — Down on Me (late)"),
      tr(3720, "Nia Vale — Last Stop"),
    ],
    comments: [
      c("nb1", "jen_leeds", "this is the one you put on in the kitchen after", 12),
      c("nb2", "vale_bag", "the grant nelson cut though", 980),
    ],
  },
  {
    id: "ancoats-afters",
    title: "Ancoats Afters",
    djId: "kieran-moss",
    show: "Northern Frequencies",
    artwork: "/art/mixes/ancoats.jpg",
    city: "Manchester",
    citySlug: "manchester",
    genres: ["Techno"],
    engine: "techno",
    bpm: 136,
    duration: 7320,
    plays: 61002,
    likes: 4881,
    uploadedAt: "2026-08-29T02:10:00Z",
    featured: true,
    seed: 13602,
    tags: ["warehouse", "peak time", "manchester"],
    description:
      "Recorded closing Warehouse 14 in late August. Two hours of rolling northern techno, no breakdowns for Instagram.",
    tracklist: [
      tr(0, "Kieran Moss — Floor Check"),
      tr(480, "Regis — Blood Witness (cut)"),
      tr(1100, "Surgeon — Returning"),
      tr(1740, "Kieran Moss — Mill Run"),
      tr(2480, "Blawan — Why They Hide Their Bodies"),
      tr(3180, "Kieran Moss — Ancoats 4"),
      tr(4020, "James Ruskin — Version"),
      tr(4860, "Kieran Moss — No Gimmicks"),
      tr(5760, "Function — Modifier"),
      tr(6540, "Kieran Moss — Sunrise Load-out"),
    ],
    comments: [
      c("a1", "mcr_mill", "this is the sound of that room. exactly.", 0),
      c("a2", "sheffield.e", "the blawan into mill run is filthy", 3180),
      c("a3", "queue_girl", "was there. still ringing", 7320),
    ],
  },
  {
    id: "warehouse-fourteen",
    title: "Warehouse 14 Warm-up",
    djId: "kieran-moss",
    show: "Northern Frequencies",
    artwork: "/art/mixes/warehouse.jpg",
    city: "Manchester",
    citySlug: "manchester",
    genres: ["Techno"],
    engine: "techno",
    bpm: 132,
    duration: 4980,
    plays: 22410,
    likes: 1602,
    uploadedAt: "2026-06-14T20:00:00Z",
    seed: 14014,
    tags: ["warmup", "hypnotic"],
    description:
      "Doors set. Hypnotic, dry, built to fill a concrete room before the heads arrive.",
    tracklist: [
      tr(0, "Kieran Moss — Doors"),
      tr(600, "Donato Dozzy — K"),
      tr(1400, "Kieran Moss — Dry Room"),
      tr(2300, "Abdulla Rashim — A1"),
      tr(3200, "Kieran Moss — Pillar 3"),
      tr(4100, "Shifted — Arranged"),
    ],
    comments: [c("w1", "ancoats_dan", "warmup of the year for me", 1400)],
  },
  {
    id: "stokes-croft-jungle",
    title: "Stokes Croft Jungle",
    djId: "yasmin-reed",
    show: "Bristol Junglist",
    artwork: "/art/mixes/bristol-houses.jpg",
    city: "Bristol",
    citySlug: "bristol",
    genres: ["Jungle", "Drum & Bass"],
    engine: "jungle",
    bpm: 162,
    duration: 5430,
    plays: 77320,
    likes: 6120,
    uploadedAt: "2026-08-08T22:00:00Z",
    featured: true,
    seed: 16208,
    tags: ["jungle", "bristol", "amen"],
    description:
      "A Bristol jungle history lesson that still functions as a rave. Amens, ragga chops, and the roll this city never gave back.",
    tracklist: [
      tr(0, "Yasmin Reed — Croft Intro"),
      tr(280, "Congo Natty — Junglist"),
      tr(640, "Remarc — R.I.P"),
      tr(1020, "Yasmin Reed — Amen Science"),
      tr(1540, "Dillinja — The Angels Fell"),
      tr(2100, "Yasmin Reed — Lanes Dub"),
      tr(2680, "LTJ Bukem — Horizons (jungle cut)"),
      tr(3240, "Yasmin Reed — Stokes VIP"),
      tr(3980, "Shy FX — Original Nuttah"),
      tr(4620, "Yasmin Reed — Home via Gloucester Rd"),
    ],
    comments: [
      c("s1", "bristol_roll", "this is church", 0),
      c("s2", "amen_girl", "RIP into amen science i stood up in the kitchen", 1020),
    ],
  },
  {
    id: "amen-corner",
    title: "Amen Corner",
    djId: "yasmin-reed",
    show: "Bristol Junglist",
    artwork: "/art/mixes/dancefloor.jpg",
    city: "Bristol",
    citySlug: "bristol",
    genres: ["Jungle"],
    engine: "jungle",
    bpm: 164,
    duration: 3900,
    plays: 19880,
    likes: 1544,
    uploadedAt: "2026-05-02T21:30:00Z",
    seed: 16402,
    tags: ["amen", "dark"],
    description: "Darker, faster, recorded in a rehearsal cellar under Stokes Croft. No MC, no mercy.",
    tracklist: [
      tr(0, "Yasmin Reed — Corner"),
      tr(400, "DJ Hype — The Chopper"),
      tr(900, "Yasmin Reed — 8-bar Terror"),
      tr(1500, "Bizzy B — 2 Bad Mice-ish"),
      tr(2200, "Yasmin Reed — Cellar Roll"),
      tr(3000, "Yasmin Reed — Out"),
    ],
    comments: [c("ac1", "dnb_dad", "proper jungle. not festival dnb", 400)],
  },
  {
    id: "chapeltown-heat",
    title: "Chapeltown Heat",
    djId: "tobi-lane",
    show: "Afters at 4",
    artwork: "/art/mixes/underpass.jpg",
    city: "Leeds",
    citySlug: "leeds",
    genres: ["Bassline", "UK Garage"],
    engine: "bassline",
    bpm: 136,
    duration: 4560,
    plays: 33410,
    likes: 2780,
    uploadedAt: "2026-08-16T03:10:00Z",
    seed: 13616,
    tags: ["bassline", "leeds", "afters"],
    description:
      "Recorded at an afters in Chapeltown that was not on any flyer. Rolling 136, skippy hats, bass that rearranges the fridge magnets.",
    tracklist: [
      tr(0, "Tobi Lane — Heat Check"),
      tr(360, "T2 — Heartbroken (bassline)"),
      tr(820, "Tobi Lane — Chapeltown VIP"),
      tr(1400, "Herve — Cheap Thrills (136)"),
      tr(2040, "Tobi Lane — 4am Rewind"),
      tr(2780, "TS7 — On the Floor"),
      tr(3480, "Tobi Lane — Bus Back"),
    ],
    comments: [
      c("ch1", "leeds_afters", "northern bassline is not a trend", 0),
      c("ch2", "rewind_kid", "PLAY THE VIP AGAIN", 1400),
    ],
  },
  {
    id: "four-am-bassline",
    title: "Afters at 4 — 026",
    djId: "tobi-lane",
    show: "Afters at 4",
    artwork: "/art/mixes/sub.jpg",
    city: "Leeds",
    citySlug: "leeds",
    genres: ["Bassline"],
    engine: "bassline",
    bpm: 138,
    duration: 3180,
    plays: 12104,
    likes: 890,
    uploadedAt: "2026-04-19T04:02:00Z",
    seed: 13819,
    tags: ["afters"],
    description: "Short, rude, and over before the sun. The monthly numbers set.",
    tracklist: [
      tr(0, "Tobi Lane — Numbers"),
      tr(480, "Tobi Lane — Fridge Magnets"),
      tr(1100, "Wideboys — Sambuca (136)"),
      tr(1800, "Tobi Lane — Close"),
      tr(2500, "Tobi Lane — Taxi"),
    ],
    comments: [c("f1", "4am_club", "this is a public service", 0)],
  },
  {
    id: "low-room-03",
    title: "Low Room 03",
    djId: "asha-quinn",
    show: "Low Room",
    artwork: "/art/mixes/glasgow.jpg",
    city: "Glasgow",
    citySlug: "glasgow",
    genres: ["Broken Beat", "House"],
    engine: "house",
    bpm: 124,
    duration: 6120,
    plays: 15440,
    likes: 1320,
    uploadedAt: "2026-07-28T21:00:00Z",
    seed: 12403,
    tags: ["broken beat", "keys", "glasgow"],
    description:
      "Keys, broken beat, and the Glasgow swing. Recorded in a tenement basement that holds 80 people and a grand's worth of monitors.",
    tracklist: [
      tr(0, "Asha Quinn — Tenement Keys"),
      tr(540, "4hero — Les Fleur (broken)"),
      tr(1200, "Asha Quinn — Finnieston"),
      tr(1980, "Bugz in the Attic — Booty La La"),
      tr(2760, "Asha Quinn — Low Room Dub"),
      tr(3600, "Kaidi Tatham — Dilla Inspired"),
      tr(4500, "Asha Quinn — Close Keys"),
      tr(5400, "Asha Quinn — Stairwell"),
    ],
    comments: [c("l1", "wee_andrea", "this city has swing. thank you", 1200)],
  },
  {
    id: "finnieston-keys",
    title: "Finnieston Keys",
    djId: "asha-quinn",
    show: "Low Room",
    artwork: "/art/mixes/mixer.jpg",
    city: "Glasgow",
    citySlug: "glasgow",
    genres: ["Broken Beat"],
    engine: "house",
    bpm: 122,
    duration: 4440,
    plays: 7210,
    likes: 610,
    uploadedAt: "2026-03-09T20:00:00Z",
    seed: 12209,
    tags: ["keys", "late"],
    description: "A quieter sister to Low Room. Almost a live keys set, almost a house mix.",
    tracklist: [
      tr(0, "Asha Quinn — Pedal Down"),
      tr(700, "Asha Quinn — Second Hand"),
      tr(1600, "Dego — Untitled"),
      tr(2500, "Asha Quinn — Close"),
      tr(3400, "Asha Quinn — Rain on Sauchiehall"),
    ],
    comments: [c("fk1", "keys_man", "the voicings on second hand", 700)],
  },
  {
    id: "digbeth-pressure",
    title: "Digbeth Pressure",
    djId: "jayce-hollow",
    show: "Signal Hours",
    artwork: "/art/mixes/pirate.jpg",
    city: "Birmingham",
    citySlug: "birmingham",
    genres: ["Grime"],
    engine: "grime",
    bpm: 140,
    duration: 3660,
    plays: 89120,
    likes: 7440,
    uploadedAt: "2026-08-01T21:00:00Z",
    featured: true,
    seed: 14001,
    tags: ["grime", "140", "midlands"],
    description:
      "Instrumental grime and 140 weaponry from a Digbeth rooftop that still has a pirate aerial on it. No MCs. The beats do the talking.",
    tracklist: [
      tr(0, "Jayce Hollow — Aerial"),
      tr(240, "Wiley — Ice Rink (instrumental)"),
      tr(560, "Jayce Hollow — Signal 19"),
      tr(980, "JME — 96 Fuckries (inst.)"),
      tr(1380, "Jayce Hollow — Digbeth VIP"),
      tr(1860, "Royal-T — 140"),
      tr(2340, "Jayce Hollow — Pressure Bag"),
      tr(2880, "Skepta — Shutdown (inst. dub)"),
      tr(3300, "Jayce Hollow — Closedown"),
    ],
    comments: [
      c("d1", "brum_pirate", "this is the midlands. write it down", 0),
      c("d2", "140_head", "signal 19 is a weapon", 560),
    ],
  },
  {
    id: "signal-hours-19",
    title: "Signal Hours 19",
    djId: "jayce-hollow",
    show: "Signal Hours",
    artwork: "/art/djs/jayce-hollow.jpg",
    city: "Birmingham",
    citySlug: "birmingham",
    genres: ["Grime", "Bass"],
    engine: "grime",
    bpm: 140,
    duration: 4140,
    plays: 25660,
    likes: 1988,
    uploadedAt: "2026-05-24T22:00:00Z",
    seed: 14019,
    tags: ["show", "140"],
    description: "The nineteenth Signal Hours. Heavier on the bass weight, lighter on the radio edits.",
    tracklist: [
      tr(0, "Jayce Hollow — Ident"),
      tr(300, "Jayce Hollow — Weight"),
      tr(900, "Trim — Trigger Finger (inst.)"),
      tr(1500, "Jayce Hollow — 19 Dub"),
      tr(2300, "P-Money — Slang like This (dub)"),
      tr(3100, "Jayce Hollow — Outro Aerial"),
    ],
    comments: [c("sh1", "signal_txt", "heavier than 18. correct", 900)],
  },
  {
    id: "all-night-social",
    title: "All Night Social — May",
    djId: "maren-cole",
    show: "All Night Social",
    artwork: "/art/mixes/vinyl.jpg",
    city: "Liverpool",
    citySlug: "liverpool",
    genres: ["Disco", "House"],
    engine: "disco",
    bpm: 122,
    duration: 8040,
    plays: 18770,
    likes: 1660,
    uploadedAt: "2026-05-17T22:00:00Z",
    seed: 12217,
    tags: ["disco", "vinyl", "all nighter"],
    description:
      "Nine-hour social compressed to a two-hour edit. Vinyl only. The Baltic Triangle with the lights still up.",
    tracklist: [
      tr(0, "Maren Cole — Doors Open"),
      tr(480, "Larry Levan — Padlock"),
      tr(1200, "Maren Cole — Baltic 12"),
      tr(2100, "Loose Joints — Is It All Over My Face"),
      tr(3000, "Maren Cole — Hands Up Edit"),
      tr(4080, "Sylvester — I Need Somebody to Love Tonight"),
      tr(5100, "Maren Cole — All Night"),
      tr(6300, "Kerri Chandler — Track 1"),
      tr(7200, "Maren Cole — Last Dance"),
    ],
    comments: [c("an1", "scouse_disco", "this is how you treat a Saturday", 0)],
  },
  {
    id: "baltic-disco",
    title: "Baltic Disco",
    djId: "maren-cole",
    show: "All Night Social",
    artwork: "/art/mixes/crates.jpg",
    city: "Liverpool",
    citySlug: "liverpool",
    genres: ["Disco"],
    engine: "disco",
    bpm: 120,
    duration: 4920,
    plays: 8440,
    likes: 702,
    uploadedAt: "2026-02-14T21:00:00Z",
    seed: 12014,
    tags: ["disco", "valentine"],
    description: "A Valentine's disco that refused to be cute. Long intros, real drums, no algorithm.",
    tracklist: [
      tr(0, "Maren Cole — Not Cute"),
      tr(700, "First Choice — Let No Man Put Asunder"),
      tr(1600, "Maren Cole — Edit 7"),
      tr(2600, "Donna Summer — I Feel Love (long)"),
      tr(3800, "Maren Cole — Home"),
    ],
    comments: [c("bd1", "vinyl_only", "the first choice placement", 700)],
  },
  {
    id: "foundry-cuts-12",
    title: "Foundry Cuts 12",
    djId: "dex-palmer",
    show: "Foundry Cuts",
    artwork: "/art/mixes/foundry.jpg",
    city: "Nottingham",
    citySlug: "nottingham",
    genres: ["Breaks"],
    engine: "breaks",
    bpm: 132,
    duration: 4380,
    plays: 10120,
    likes: 880,
    uploadedAt: "2026-06-21T22:00:00Z",
    seed: 13221,
    tags: ["breaks", "nu-skool"],
    description: "Nu-skool breaks, electro dirt, and the Nottingham swing Dex has been sitting on since '01.",
    tracklist: [
      tr(0, "Dex Palmer — Foundry Ident"),
      tr(360, "Stanton Warriors — Da Virus"),
      tr(900, "Dex Palmer — Sneinton Wobble"),
      tr(1560, "Plump DJs — Big Groovy Fucker"),
      tr(2280, "Dex Palmer — Cut 12"),
      tr(3120, "Adam Freeland — We Want Your Soul"),
      tr(3780, "Dex Palmer — Load out"),
    ],
    comments: [c("fc1", "breaks_dad", "not dead. never was.", 0)],
  },
  {
    id: "sneinton-breaks",
    title: "Sneinton Breaks",
    djId: "dex-palmer",
    show: "Foundry Cuts",
    artwork: "/art/djs/dex-palmer.jpg",
    city: "Nottingham",
    citySlug: "nottingham",
    genres: ["Breaks"],
    engine: "breaks",
    bpm: 134,
    duration: 3600,
    plays: 5330,
    likes: 410,
    uploadedAt: "2026-01-18T21:00:00Z",
    seed: 13418,
    tags: ["breaks"],
    description: "A tighter, uglier hour. More electro, less festival.",
    tracklist: [
      tr(0, "Dex Palmer — Ugly Swing"),
      tr(600, "Dex Palmer — 01 Bag"),
      tr(1400, "Krafty Kuts — Smash"),
      tr(2200, "Dex Palmer — Notch Filter"),
      tr(3000, "Dex Palmer — Out"),
    ],
    comments: [c("sb1", "notts_floor", "this one doesn't get enough plays", 0)],
  },
  {
    id: "east-end-pressure",
    title: "East End Pressure 11",
    djId: "saffron-ibe",
    show: "East End Pressure",
    artwork: "/art/mixes/peckham-street.jpg",
    city: "London",
    citySlug: "london",
    genres: ["UK Funky", "House"],
    engine: "funky",
    bpm: 130,
    duration: 5040,
    plays: 41220,
    likes: 3550,
    uploadedAt: "2026-08-25T21:30:00Z",
    featured: true,
    seed: 13011,
    tags: ["funky", "hackney", "percussion"],
    description:
      "UK funky that still remembers it came from garage. Percussion, soca tempo, Hackney pressure. The overground mix.",
    tracklist: [
      tr(0, "Saffron Ibe — Overground"),
      tr(360, "Crazy Cousinz — Do You Mind"),
      tr(840, "Saffron Ibe — Pressure 11"),
      tr(1440, "Kukie D — In da Ghetto"),
      tr(2100, "Saffron Ibe — E8 VIP"),
      tr(2820, "Cooly G — Narst"),
      tr(3480, "Saffron Ibe — Perc Bag"),
      tr(4200, "Saffron Ibe — Last Carriage"),
    ],
    comments: [
      c("ee1", "hackney_wick", "funky never left, the blogs did", 0),
      c("ee2", "perc_head", "e8 vip is the one", 2100),
    ],
  },
  {
    id: "hackney-funky",
    title: "Hackney Funky",
    djId: "saffron-ibe",
    show: "East End Pressure",
    artwork: "/art/djs/saffron-ibe.jpg",
    city: "London",
    citySlug: "london",
    genres: ["UK Funky"],
    engine: "funky",
    bpm: 128,
    duration: 3960,
    plays: 16880,
    likes: 1210,
    uploadedAt: "2026-04-04T22:00:00Z",
    seed: 12804,
    tags: ["funky"],
    description: "A straight funky hour. No house tourism. If you know, you know.",
    tracklist: [
      tr(0, "Saffron Ibe — Know"),
      tr(480, "Saffron Ibe — Wick Dub"),
      tr(1200, "Donae'o — Party Hard"),
      tr(1980, "Saffron Ibe — Tempo"),
      tr(2880, "Saffron Ibe — Home via Victoria"),
    ],
    comments: [c("hf1", "e8_girl", "party hard in 2026 still works. correct", 1200)],
  },
  {
    id: "blade-09",
    title: "Blade 09",
    djId: "ellis-crowe",
    show: "Blade",
    artwork: "/art/mixes/foundry.jpg",
    city: "Sheffield",
    citySlug: "sheffield",
    genres: ["Industrial", "Techno"],
    engine: "industrial",
    bpm: 138,
    duration: 6660,
    plays: 28770,
    likes: 2410,
    uploadedAt: "2026-07-04T23:00:00Z",
    seed: 13809,
    tags: ["industrial", "sheffield", "foundry"],
    description:
      "Recorded in a Kelham foundry that is only sometimes a club. Steam, steel, 138. Ellis does not talk on the mic.",
    tracklist: [
      tr(0, "Ellis Crowe — Shift Start"),
      tr(600, "Downwards — Untitled"),
      tr(1400, "Ellis Crowe — Blade 9"),
      tr(2300, "Regis — Blood Into Gold"),
      tr(3200, "Ellis Crowe — Steam"),
      tr(4200, "Surgeon — Fixed Action Pattern"),
      tr(5300, "Ellis Crowe — Knock Off"),
    ],
    comments: [c("b1", "kelham_night", "this is the sound of that building", 0)],
  },
  {
    id: "kelham-steel",
    title: "Kelham Steel",
    djId: "ellis-crowe",
    show: "Blade",
    artwork: "/art/djs/ellis-crowe.jpg",
    city: "Sheffield",
    citySlug: "sheffield",
    genres: ["Industrial"],
    engine: "industrial",
    bpm: 140,
    duration: 4200,
    plays: 9440,
    likes: 770,
    uploadedAt: "2026-02-28T22:00:00Z",
    seed: 14028,
    tags: ["industrial"],
    description: "Faster, drier, more Machine. A midweek foundry test.",
    tracklist: [
      tr(0, "Ellis Crowe — Test"),
      tr(700, "Ellis Crowe — Dry"),
      tr(1600, "Ancient Methods — The City Gates"),
      tr(2600, "Ellis Crowe — Steel"),
      tr(3400, "Ellis Crowe — Out"),
    ],
    comments: [c("ks1", "blade_txt", "put this on a soundsystem or don't", 0)],
  },
  {
    id: "civic-bass-22",
    title: "Civic Bass 22",
    djId: "rio-bennett",
    show: "Civic Bass",
    artwork: "/art/mixes/cardiff.jpg",
    city: "Cardiff",
    citySlug: "cardiff",
    genres: ["Drum & Bass"],
    engine: "dnb",
    bpm: 174,
    duration: 5280,
    plays: 22100,
    likes: 1888,
    uploadedAt: "2026-08-12T21:00:00Z",
    seed: 17422,
    tags: ["dnb", "cardiff", "rollers"],
    description:
      "Liquid into rollers into a little tear-out, without the identity crisis. Cardiff civic centre after dark.",
    tracklist: [
      tr(0, "Rio Bennett — Civic Ident"),
      tr(360, "Calibre — Mr. Maverick"),
      tr(900, "Rio Bennett — Grangetown Roll"),
      tr(1560, "dBridge — Inner Disbelief"),
      tr(2280, "Rio Bennett — 22 VIP"),
      tr(3000, "Alix Perez — Annie's Song"),
      tr(3720, "Rio Bennett — Tear a Little"),
      tr(4500, "Rio Bennett — Taxi Bay"),
    ],
    comments: [c("cb1", "wales_roll", "cardiff not a satellite of bristol. thanks rio", 0)],
  },
  {
    id: "grangetown-roll",
    title: "Grangetown Roll",
    djId: "rio-bennett",
    show: "Civic Bass",
    artwork: "/art/djs/rio-bennett.jpg",
    city: "Cardiff",
    citySlug: "cardiff",
    genres: ["Drum & Bass"],
    engine: "dnb",
    bpm: 172,
    duration: 3840,
    plays: 8088,
    likes: 640,
    uploadedAt: "2026-03-22T21:00:00Z",
    seed: 17222,
    tags: ["rollers"],
    description: "All rollers, no peak-time theatrics. For the drive along the bay.",
    tracklist: [
      tr(0, "Rio Bennett — Bay"),
      tr(600, "Rio Bennett — Roll 3"),
      tr(1400, "LSB — 7th Day"),
      tr(2300, "Rio Bennett — Civic Late"),
      tr(3100, "Rio Bennett — Home"),
    ],
    comments: [c("gr1", "bay_drive", "this is a car mix. correctly", 0)],
  },
  {
    id: "seafront-closed",
    title: "Seafront Closed",
    djId: "lana-voss",
    show: "Seafront Closed",
    artwork: "/art/mixes/seafront.jpg",
    city: "Brighton",
    citySlug: "brighton",
    genres: ["Electro", "Breaks"],
    engine: "electro",
    bpm: 128,
    duration: 4680,
    plays: 13320,
    likes: 1110,
    uploadedAt: "2026-07-19T01:20:00Z",
    seed: 12819,
    tags: ["electro", "brighton", "afters"],
    description:
      "When the seafront clubs have packed down and the wind is doing percussion. Electro, breaks, salt air.",
    tracklist: [
      tr(0, "Lana Voss — Promenade"),
      tr(420, "DMX Krew — Come to Me"),
      tr(980, "Lana Voss — Kemptown"),
      tr(1680, "Dopplereffekt — Infophysix"),
      tr(2400, "Lana Voss — Storm Edit"),
      tr(3180, "Anthony Rother — Destroy Him My Robots"),
      tr(3900, "Lana Voss — Last Shelter"),
    ],
    comments: [c("sf1", "kemptown_3am", "the storm edit is the one", 2400)],
  },
  {
    id: "kemptown-electro",
    title: "Kemptown Electro",
    djId: "lana-voss",
    show: "Seafront Closed",
    artwork: "/art/djs/lana-voss.jpg",
    city: "Brighton",
    citySlug: "brighton",
    genres: ["Electro"],
    engine: "electro",
    bpm: 126,
    duration: 3540,
    plays: 6110,
    likes: 505,
    uploadedAt: "2026-01-31T23:00:00Z",
    seed: 12631,
    tags: ["electro"],
    description: "A cold January electro hour. Machines, no vocals, sea in the distance.",
    tracklist: [
      tr(0, "Lana Voss — January"),
      tr(600, "Lana Voss — Machines"),
      tr(1400, "Aux 88 — Direct Drive"),
      tr(2200, "Lana Voss — Pier"),
      tr(2900, "Lana Voss — Closed"),
    ],
    comments: [c("ke1", "pier_closed", "january electro is a genre now", 0)],
  },
];

export const LIVE_SHOWS: LiveShow[] = [
  {
    id: "live-nia-cellar",
    djId: "nia-vale",
    title: "Peckham Steppers — Live from The Cellar",
    venue: "The Cellar, Peckham",
    city: "London",
    citySlug: "london",
    artwork: "/art/venues/cellar.jpg",
    genres: ["UK Garage", "2-Step"],
    engine: "ukg",
    bpm: 132,
    listeners: 1842,
    durationMin: 180,
    status: "live",
    seed: 90001,
    advertised: true,
    description: "Nia Vale live in the basement. 2-step, unreleased dubs, south London heat.",
    tracklist: [
      tr(0, "Nia Vale — Live warmup"),
      tr(720, "Wookie — Battle"),
      tr(1500, "Nia Vale — Unreleased 7"),
      tr(2400, "MJ Cole — Sincere"),
      tr(3300, "Nia Vale — Cellar VIP"),
      tr(4200, "Artful Dodger — Moving Too Fast"),
      tr(5400, "Nia Vale — Peak"),
      tr(7200, "Nia Vale — Closedown"),
    ],
  },
  {
    id: "live-kieran-wh14",
    djId: "kieran-moss",
    title: "Northern Frequencies — Warehouse 14",
    venue: "Warehouse 14, Ancoats",
    city: "Manchester",
    citySlug: "manchester",
    artwork: "/art/venues/warehouse14.jpg",
    genres: ["Techno"],
    engine: "techno",
    bpm: 136,
    listeners: 2610,
    durationMin: 210,
    status: "live",
    seed: 90002,
    description: "Peak-time from the mill. Kieran Moss, no lights show, just the room.",
    tracklist: [
      tr(0, "Kieran Moss — Floor"),
      tr(900, "Surgeon — Returning"),
      tr(2100, "Kieran Moss — Mill Live"),
      tr(3600, "Blawan — Why They Hide"),
      tr(5400, "Kieran Moss — Ancoats Live"),
      tr(7800, "Function — Modifier"),
    ],
  },
  {
    id: "live-yasmin-lanes",
    djId: "yasmin-reed",
    title: "Bristol Junglist — The Lanes",
    venue: "The Lanes, Bristol",
    city: "Bristol",
    citySlug: "bristol",
    artwork: "/art/venues/lanes.jpg",
    genres: ["Jungle", "Drum & Bass"],
    engine: "jungle",
    bpm: 164,
    listeners: 1330,
    durationMin: 150,
    status: "live",
    seed: 90003,
    description: "Yasmin Reed in the cellar under Stokes Croft. Amens up.",
    tracklist: [
      tr(0, "Yasmin Reed — Lanes warmup"),
      tr(600, "Congo Natty — Junglist"),
      tr(1500, "Yasmin Reed — Amen Live"),
      tr(2700, "Remarc — RIP"),
      tr(4200, "Yasmin Reed — Croft VIP"),
      tr(6000, "Shy FX — Original Nuttah"),
    ],
  },
  {
    id: "up-tobi-leeds",
    djId: "tobi-lane",
    title: "Afters at 4 — Chapeltown",
    venue: "Foundry, Leeds",
    city: "Leeds",
    citySlug: "leeds",
    artwork: "/art/mixes/underpass.jpg",
    genres: ["Bassline"],
    engine: "bassline",
    bpm: 136,
    listeners: 0,
    durationMin: 180,
    status: "upcoming",
    startsAt: upcomingISO(0, 23, 0),
    seed: 91001,
    description: "Tobi Lane, bassline afters. Doors when the rest of the city goes home.",
    tracklist: [],
  },
  {
    id: "up-saffron-hackney",
    djId: "saffron-ibe",
    title: "East End Pressure — Live",
    venue: "E8 Social, Hackney",
    city: "London",
    citySlug: "london",
    artwork: "/art/mixes/peckham-street.jpg",
    genres: ["UK Funky"],
    engine: "funky",
    bpm: 130,
    listeners: 0,
    durationMin: 150,
    status: "upcoming",
    startsAt: upcomingISO(2, 21, 0),
    seed: 91002,
    description: "Saffron Ibe, UK funky, east London percussion.",
    tracklist: [],
  },
  {
    id: "up-ellis-sheffield",
    djId: "ellis-crowe",
    title: "Blade — Kelham Foundry",
    venue: "Kelham Foundry, Sheffield",
    city: "Sheffield",
    citySlug: "sheffield",
    artwork: "/art/mixes/foundry.jpg",
    genres: ["Industrial"],
    engine: "industrial",
    bpm: 138,
    listeners: 0,
    durationMin: 180,
    status: "upcoming",
    startsAt: upcomingISO(4, 22, 0),
    seed: 91003,
    description: "Ellis Crowe, industrial techno, steam and steel.",
    tracklist: [],
  },
  {
    id: "up-jayce-digbeth",
    djId: "jayce-hollow",
    title: "Signal Hours — Digbeth",
    venue: "Signal, Digbeth",
    city: "Birmingham",
    citySlug: "birmingham",
    artwork: "/art/mixes/pirate.jpg",
    genres: ["Grime"],
    engine: "grime",
    bpm: 140,
    listeners: 0,
    durationMin: 120,
    status: "upcoming",
    startsAt: upcomingISO(6, 21, 30),
    seed: 91004,
    description: "Jayce Hollow, 140, rooftop aerial still up.",
    tracklist: [],
  },
  {
    id: "up-asha-glasgow",
    djId: "asha-quinn",
    title: "Low Room — Finnieston",
    venue: "Low Room, Glasgow",
    city: "Glasgow",
    citySlug: "glasgow",
    artwork: "/art/mixes/glasgow.jpg",
    genres: ["Broken Beat"],
    engine: "house",
    bpm: 124,
    listeners: 0,
    durationMin: 180,
    status: "upcoming",
    startsAt: upcomingISO(8, 20, 0),
    seed: 91005,
    description: "Asha Quinn, keys and broken beat in a tenement basement.",
    tracklist: [],
  },
];

function upcomingISO(daysFromTue: number, hour: number, minute: number) {
  // Anchor to Tue 1 Sep 2026 so the schedule is stable in this build.
  const base = Date.UTC(2026, 8, 1, 0, 0, 0);
  const d = new Date(base + daysFromTue * 86400000);
  d.setUTCHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const CHAT_SEED: Record<string, { user: string; text: string }[]> = {
  "live-nia-cellar": [
    { user: "bus_36", text: "that skip though" },
    { user: "southside.step", text: "what was the white label" },
    { user: "jen_leeds", text: "peckham's finest" },
    { user: "vale_bag", text: "rewind that" },
    { user: "kieran.m", text: "heavy" },
    { user: "e8_girl", text: "the sub in this room" },
    { user: "anon_4", text: "who's on next" },
    { user: "steppers", text: "this is the one" },
  ],
  "live-kieran-wh14": [
    { user: "mcr_mill", text: "the room is gone" },
    { user: "ancoats_dan", text: "no lights. correct" },
    { user: "queue_girl", text: "been in since doors" },
    { user: "sheffield.e", text: "this filter" },
    { user: "pillar_3", text: "warehouse techno not festival techno" },
    { user: "loadout", text: "sunrise still two hours" },
  ],
  "live-yasmin-lanes": [
    { user: "bristol_roll", text: "AMEN" },
    { user: "amen_girl", text: "the lanes is sweating" },
    { user: "dnb_dad", text: "proper jungle" },
    { user: "croft_kid", text: "rewind" },
    { user: "glos_rd", text: "this city" },
  ],
};

export function getDj(id: string) {
  return WORLD_DJS.find((d) => d.id === id) ?? worldDj(id);
}

export function getMix(id: string) {
  return MIXES.find((m) => m.id === id);
}

export function getLive(id: string) {
  return WORLD_LIVE.find((s) => s.id === id) ?? worldLive(id);
}

export function mixesByDj(djId: string) {
  return MIXES.filter((m) => m.djId === djId);
}

export function mixesByGenre(genre: string) {
  return MIXES.filter((m) => m.genres.some((g) => g.toLowerCase() === genre.toLowerCase()));
}

export function mixesByCity(slug: string) {
  return MIXES.filter((m) => m.citySlug === slug);
}

export function liveNow() {
  return WORLD_LIVE;
}

export function liveUpcoming(): LiveShow[] {
  return [];
}

export function featuredMixes() {
  return MIXES.filter((m) => m.featured);
}

export function trendingMixes() {
  return [...MIXES].sort((a, b) => b.likes - a.likes);
}

export function newMixes() {
  return [...MIXES].sort((a, b) => +new Date(b.uploadedAt) - +new Date(a.uploadedAt));
}

export function chartMixes() {
  return [...MIXES].sort((a, b) => b.plays - a.plays);
}

export function relatedMixes(mix: Mix, n = 6) {
  return MIXES.filter(
    (m) => m.id !== mix.id && (m.djId === mix.djId || m.genres.some((g) => mix.genres.includes(g))),
  ).slice(0, n);
}

export function searchCatalog(q: string) {
  const s = q.trim().toLowerCase();
  if (!s) return { mixes: [] as Mix[], djs: [] as Dj[], live: [] as LiveShow[] };
  const hit = (parts: string[]) => parts.some((p) => p.toLowerCase().includes(s));
  return {
    mixes: [] as Mix[],
    djs: WORLD_DJS.filter((d) => hit([d.name, d.handle, d.city, d.show, d.genres.join(" "), d.bio])),
    live: WORLD_LIVE.filter((l) =>
      hit([l.title, l.venue, l.city, l.genres.join(" "), getDj(l.djId)?.name ?? ""]),
    ),
  };
}

export function liveOffsetSec(show: LiveShow) {
  if (show.status !== "live") return 0;
  const day = Math.floor(Date.now() / 86400000);
  const h = hashString(show.id + String(day));
  const max = Math.max(12, show.durationMin - 20);
  const startedAgoMin = 16 + (h % max);
  return Math.min(startedAgoMin * 60, (show.durationMin - 8) * 60);
}

export function currentTrack(tracklist: Track[], t: number) {
  if (!tracklist.length) return null;
  let cur = tracklist[0];
  for (const trk of tracklist) {
    if (trk.t <= t) cur = trk;
    else break;
  }
  return cur;
}

export function genreToEngine(genre: string): EngineGenre {
  const g = genre.toLowerCase();
  if (g.includes("garage") || g.includes("2-step") || g.includes("2 step")) return "ukg";
  if (g.includes("jungle")) return "jungle";
  if (g.includes("drum")) return "dnb";
  if (g.includes("grime") || g.includes("bass")) return "grime";
  if (g.includes("techno") && g.includes("industrial")) return "industrial";
  if (g.includes("industrial")) return "industrial";
  if (g.includes("techno")) return "techno";
  if (g.includes("disco")) return "disco";
  if (g.includes("funky")) return "funky";
  if (g.includes("bassline")) return "bassline";
  if (g.includes("break")) return "breaks";
  if (g.includes("electro")) return "electro";
  return "house";
}

export const GENRE_SLUGS = GENRES.map((g) => ({
  name: g,
  slug: g.toLowerCase().replace(/ & /g, "-").replace(/\s+/g, "-"),
}));

export function genreFromSlug(slug: string) {
  return GENRE_SLUGS.find((g) => g.slug === slug)?.name;
}
