/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BoothRouteImport } from './routes/booth'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as OpenRouteImport } from './routes/open'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WowRouteImport } from './routes/wow'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as DjIdRouteImport } from './routes/dj.$id'
import { Route as GenreSlugRouteImport } from './routes/genre.$slug'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as MembershipSuccessRouteImport } from './routes/membership.success'
import { Route as MerchSuccessRouteImport } from './routes/merch.success'
import { Route as MixIdRouteImport } from './routes/mix.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRadioIdRouteImport } from './routes/api/radio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothRoute = BoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WowRoute = WowRouteImport.update({
  id: '/wow',
  path: '/wow',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DjIdRoute = DjIdRouteImport.update({
  id: '/dj/$id',
  path: '/dj/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreSlugRoute = GenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiveRoute,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LiveRoute,
} as any)
const MembershipSuccessRoute = MembershipSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => MembershipRoute,
} as any)
const MerchSuccessRoute = MerchSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => MerchRoute,
} as any)
const MixIdRoute = MixIdRouteImport.update({
  id: '/mix/$id',
  path: '/mix/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadioIdRoute = ApiRadioIdRouteImport.update({
  id: '/api/radio/$id',
  path: '/api/radio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booth': typeof BoothRoute
  '/charts': typeof ChartsRoute
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/merch': typeof MerchRouteWithChildren
  '/open': typeof OpenRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/safety': typeof SafetyRoute
  '/school': typeof SchoolRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/wow': typeof WowRoute
  '/city/$slug': typeof CitySlugRoute
  '/dj/$id': typeof DjIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/live/$id': typeof LiveIdRoute
  '/membership/success': typeof MembershipSuccessRoute
  '/merch/success': typeof MerchSuccessRoute
  '/mix/$id': typeof MixIdRoute
  '/live/': typeof LiveIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/radio/$id': typeof ApiRadioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booth': typeof BoothRoute
  '/charts': typeof ChartsRoute
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/merch': typeof MerchRouteWithChildren
  '/open': typeof OpenRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/safety': typeof SafetyRoute
  '/school': typeof SchoolRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/wow': typeof WowRoute
  '/city/$slug': typeof CitySlugRoute
  '/dj/$id': typeof DjIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/live/$id': typeof LiveIdRoute
  '/membership/success': typeof MembershipSuccessRoute
  '/merch/success': typeof MerchSuccessRoute
  '/mix/$id': typeof MixIdRoute
  '/live': typeof LiveIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/radio/$id': typeof ApiRadioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booth': typeof BoothRoute
  '/charts': typeof ChartsRoute
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/merch': typeof MerchRouteWithChildren
  '/open': typeof OpenRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/safety': typeof SafetyRoute
  '/school': typeof SchoolRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/wow': typeof WowRoute
  '/city/$slug': typeof CitySlugRoute
  '/dj/$id': typeof DjIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/live/$id': typeof LiveIdRoute
  '/membership/success': typeof MembershipSuccessRoute
  '/merch/success': typeof MerchSuccessRoute
  '/mix/$id': typeof MixIdRoute
  '/live/': typeof LiveIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/radio/$id': typeof ApiRadioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/booth'
    | '/charts'
    | '/community'
    | '/cookies'
    | '/library'
    | '/live'
    | '/login'
    | '/membership'
    | '/merch'
    | '/open'
    | '/privacy'
    | '/releases'
    | '/safety'
    | '/school'
    | '/search'
    | '/shop'
    | '/software'
    | '/terms'
    | '/trade'
    | '/wow'
    | '/city/$slug'
    | '/dj/$id'
    | '/genre/$slug'
    | '/live/$id'
    | '/membership/success'
    | '/merch/success'
    | '/mix/$id'
    | '/live/'
    | '/api/auth/$'
    | '/api/radio/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/booth'
    | '/charts'
    | '/community'
    | '/cookies'
    | '/library'
    | '/login'
    | '/membership'
    | '/merch'
    | '/open'
    | '/privacy'
    | '/releases'
    | '/safety'
    | '/school'
    | '/search'
    | '/shop'
    | '/software'
    | '/terms'
    | '/trade'
    | '/wow'
    | '/city/$slug'
    | '/dj/$id'
    | '/genre/$slug'
    | '/live/$id'
    | '/membership/success'
    | '/merch/success'
    | '/mix/$id'
    | '/live'
    | '/api/auth/$'
    | '/api/radio/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/booth'
    | '/charts'
    | '/community'
    | '/cookies'
    | '/library'
    | '/live'
    | '/login'
    | '/membership'
    | '/merch'
    | '/open'
    | '/privacy'
    | '/releases'
    | '/safety'
    | '/school'
    | '/search'
    | '/shop'
    | '/software'
    | '/terms'
    | '/trade'
    | '/wow'
    | '/city/$slug'
    | '/dj/$id'
    | '/genre/$slug'
    | '/live/$id'
    | '/membership/success'
    | '/merch/success'
    | '/mix/$id'
    | '/live/'
    | '/api/auth/$'
    | '/api/radio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BoothRoute: typeof BoothRoute
  ChartsRoute: typeof ChartsRoute
  CommunityRoute: typeof CommunityRoute
  CookiesRoute: typeof CookiesRoute
  LibraryRoute: typeof LibraryRoute
  LiveRoute: typeof LiveRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRouteWithChildren
  MerchRoute: typeof MerchRouteWithChildren
  OpenRoute: typeof OpenRoute
  PrivacyRoute: typeof PrivacyRoute
  ReleasesRoute: typeof ReleasesRoute
  SafetyRoute: typeof SafetyRoute
  SchoolRoute: typeof SchoolRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SoftwareRoute: typeof SoftwareRoute
  TermsRoute: typeof TermsRoute
  TradeRoute: typeof TradeRoute
  WowRoute: typeof WowRoute
  CitySlugRoute: typeof CitySlugRoute
  DjIdRoute: typeof DjIdRoute
  GenreSlugRoute: typeof GenreSlugRoute
  MixIdRoute: typeof MixIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRadioIdRoute: typeof ApiRadioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth': {
      id: '/booth'
      path: '/booth'
      fullPath: '/booth'
      preLoaderRoute: typeof BoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wow': {
      id: '/wow'
      path: '/wow'
      fullPath: '/wow'
      preLoaderRoute: typeof WowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj/$id': {
      id: '/dj/$id'
      path: '/dj/$id'
      fullPath: '/dj/$id'
      preLoaderRoute: typeof DjIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$slug': {
      id: '/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/genre/$slug'
      preLoaderRoute: typeof GenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof LiveRoute
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof LiveRoute
    }
    '/membership/success': {
      id: '/membership/success'
      path: '/success'
      fullPath: '/membership/success'
      preLoaderRoute: typeof MembershipSuccessRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/merch/success': {
      id: '/merch/success'
      path: '/success'
      fullPath: '/merch/success'
      preLoaderRoute: typeof MerchSuccessRouteImport
      parentRoute: typeof MerchRoute
    }
    '/mix/$id': {
      id: '/mix/$id'
      path: '/mix/$id'
      fullPath: '/mix/$id'
      preLoaderRoute: typeof MixIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radio/$id': {
      id: '/api/radio/$id'
      path: '/api/radio/$id'
      fullPath: '/api/radio/$id'
      preLoaderRoute: typeof ApiRadioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LiveRouteChildren {
  LiveIdRoute: typeof LiveIdRoute
  LiveIndexRoute: typeof LiveIndexRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveIdRoute: LiveIdRoute,
  LiveIndexRoute: LiveIndexRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

interface MembershipRouteChildren {
  MembershipSuccessRoute: typeof MembershipSuccessRoute
}

const MembershipRouteChildren: MembershipRouteChildren = {
  MembershipSuccessRoute: MembershipSuccessRoute,
}

const MembershipRouteWithChildren = MembershipRoute._addFileChildren(
  MembershipRouteChildren,
)

interface MerchRouteChildren {
  MerchSuccessRoute: typeof MerchSuccessRoute
}

const MerchRouteChildren: MerchRouteChildren = {
  MerchSuccessRoute: MerchSuccessRoute,
}

const MerchRouteWithChildren = MerchRoute._addFileChildren(MerchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BoothRoute: BoothRoute,
  ChartsRoute: ChartsRoute,
  CommunityRoute: CommunityRoute,
  CookiesRoute: CookiesRoute,
  LibraryRoute: LibraryRoute,
  LiveRoute: LiveRouteWithChildren,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRouteWithChildren,
  MerchRoute: MerchRouteWithChildren,
  OpenRoute: OpenRoute,
  PrivacyRoute: PrivacyRoute,
  ReleasesRoute: ReleasesRoute,
  SafetyRoute: SafetyRoute,
  SchoolRoute: SchoolRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SoftwareRoute: SoftwareRoute,
  TermsRoute: TermsRoute,
  TradeRoute: TradeRoute,
  WowRoute: WowRoute,
  CitySlugRoute: CitySlugRoute,
  DjIdRoute: DjIdRoute,
  GenreSlugRoute: GenreSlugRoute,
  MixIdRoute: MixIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRadioIdRoute: ApiRadioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
